-- begin BICYCLESHOP_CLIENT
create unique index IDX_BICYCLESHOP_CLIENT_UNIQ_PHONE_NUMBER on BICYCLESHOP_CLIENT (PHONE_NUMBER) ^
create unique index IDX_BICYCLESHOP_CLIENT_UNIQ_EMAIL on BICYCLESHOP_CLIENT (EMAIL) ^
-- end BICYCLESHOP_CLIENT
-- begin BICYCLESHOP_MECHANIC
alter table BICYCLESHOP_MECHANIC add constraint FK_BICYCLESHOP_MECHANIC_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_BICYCLESHOP_MECHANIC_USER on BICYCLESHOP_MECHANIC (USER_ID)^
-- end BICYCLESHOP_MECHANIC
-- begin BICYCLESHOP_SPARE_PART
create unique index IDX_BICYCLESHOP_SPARE_PART_UNIQ_TITLE on BICYCLESHOP_SPARE_PART (TITLE) ^
-- end BICYCLESHOP_SPARE_PART
-- begin BICYCLESHOP_ORDER
alter table BICYCLESHOP_ORDER add constraint FK_BICYCLESHOP_ORDER_CLIENT foreign key (CLIENT_ID) references BICYCLESHOP_CLIENT(ID)^
alter table BICYCLESHOP_ORDER add constraint FK_BICYCLESHOP_ORDER_MECHANIC foreign key (MECHANIC_ID) references BICYCLESHOP_MECHANIC(ID)^
create index IDX_BICYCLESHOP_ORDER_MECHANIC on BICYCLESHOP_ORDER (MECHANIC_ID)^
create index IDX_BICYCLESHOP_ORDER_CLIENT on BICYCLESHOP_ORDER (CLIENT_ID)^
-- end BICYCLESHOP_ORDER
-- begin BICYCLESHOP_ORDER_SPARE_PART_LINK
alter table BICYCLESHOP_ORDER_SPARE_PART_LINK add constraint FK_BOSPL_ORDER foreign key (ORDER_ID) references BICYCLESHOP_ORDER(ID)^
alter table BICYCLESHOP_ORDER_SPARE_PART_LINK add constraint FK_BOSPL_SPARE_PART foreign key (SPARE_PART_ID) references BICYCLESHOP_SPARE_PART(ID)^
-- end BICYCLESHOP_ORDER_SPARE_PART_LINK
